### ISSUE TITLE
Merge typed objects

### ISSUE THREAD

**Issue by Jogai** [matthieujabbour/diox-cloner#2]
I'm trying to merge two ts-typed objects, and I'm pretty sure this worked before, but now I get an error "Arguments must both be plain objects".

See here: https://stackblitz.com/edit/typescript-ehovev?devtoolsheight=10

**Comment by matthieujabbour** [comment]
Hi @Jogai , sorry for the late reply, I'll have a look at it.

**Comment by matthieujabbour** [comment]
@Jogai An error is indeed thrown as objects that are class instances cannot be merged as plain objects. It makes sense that instances cannot be manipulated the same way we do with plain object, as it would potentially break they specs, attributes visibility, and so on.
